version: "{branch} {build}"
init:
  - git config --global core.autocrlf true
before_build:
  - cmd: mkdir C:\gogs && git clone https://github.com/gogits/gogs.git C:\gogs
  - cmd: mkdir C:\dep && git clone https://github.com/golang/dep.git C:\dep
  - cmd: mkdir C:\examples && git clone https://github.com/gogradle/examples.git C:\examples
build_script:
  - gradlew check --info --no-daemon --stacktrace
environment:
  JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
  JAVA_OPTS: -Xmx1800m -XX:MaxPermSize=256m
  GOGS_DIR: C:\gogs
  DEP_DIR: C:\dep
  EXAMPLES_DIR: C:\examples
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
matrix:
  fast_finish: true
